# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aCAPf1f2_cpp <- function(Jfunc1_ext_ls, Jfunc2_ext_ls, alpha, max_drv) {
    .Call(`_aCAP_aCAPf1f2_cpp`, Jfunc1_ext_ls, Jfunc2_ext_ls, alpha, max_drv)
}

